contactSystem/Models/ContatoModels.cs
namespace contactSystem.Models
{
    public class ContatoModels
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Number { get; set; }
    }
}

contactSystem/Models/ErrorViewModel.cs
using System;

namespace contactSystem.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

contactSystem/Controllers/ContatoController.cs
using contactSystem.Models;
using contactSystem.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace contactSystem.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepository _contatoRepository;
        public ContatoController(IContatoRepository contatoRepository)
        {
            _contatoRepository = contatoRepository;
        }
        //Método principal da controller
        public IActionResult Index()
        {
            var contatos = _contatoRepository.GetAll();
            return View(contatos);
        }
        public IActionResult Criar()
        {
            return View();
        }
        public IActionResult Editar(int id)
        {
            ContatoModels contato = _contatoRepository.Get(id);
            return View(contato);
        }
        public IActionResult Excluir(int id)
        {
            ContatoModels contato = _contatoRepository.Get(id);
            return View(contato);
        }


        //HTTP METHODS
        [HttpPost]
        public IActionResult Add(ContatoModels contato)
        {
            _contatoRepository.Add(contato);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Alter(ContatoModels contato)
        {
            _contatoRepository.Alter(contato);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _contatoRepository.Delete(id);
            return RedirectToAction("Index");

        }

    }
}

contactSystem/Controllers/HomeController.cs
using contactSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace contactSystem.Controllers
{
    public class HomeController : Controller
    {
    
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

contactSystem/Views/Contato/Criar.cshtml
@model ContatoModels

@{
    ViewData["Title"] = "Novo Contato";
}

<div class="text-center">
    <h1 class="display-4">CADASTRAR CONTATO</h1>
</div>

<form asp-controller="Contato" asp-action="Add" method="post">
    <div class="mb-3">
      <label for="name" class="form-label">NOME:</label>
      <input type="text" asp-for="Name" class="form-control" id="name" placeholder="Nome...">
    </div>
    <div class="mb-3">
      <label for="name" class="form-label">E-MAIL:</label>
      <input type="email" asp-for="Email" class="form-control" id="email" placeholder="Email...">
    </div>
    <div class="mb-3">
      <label for="name" class="form-label">TELEFONE:</label>
      <input type="number" asp-for="Number" class="form-control" id="cel" placeholder="Telefone...">
    </div>
    <button type="submit" class="btn btn-primary btn-block" style="margin-top:10px;">CADASTRAR</button>
    <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">VOLTAR</a>
</form>

contactSystem/Views/Contato/Editar.cshtml
@model ContatoModels
@{
    ViewData["Title"] = "Editar Contato";
}

<div class="text-center">
    <h1 class="display-4">EDITAR CONTATO</h1>
</div>

<form  asp-controller="Contato" asp-action="Alter" method="post">
    <input type="hidden" asp-for="Id">
    <div class="mb-3">
      <label for="name" class="form-label">NOME:</label>
      <input type="text" asp-for="Name" class="form-control" id="name" placeholder="Nome...">
    </div>
    <div class="mb-3">
      <label for="name" class="form-label">E-MAIL:</label>
      <input type="email" asp-for="Email" class="form-control" id="email" placeholder="Email...">
    </div>
    <div class="mb-3">
      <label for="name" class="form-label">TELEFONE:</label>
      <input type="number" asp-for="Number" class="form-control" id="cel" placeholder="Telefone...">
    </div>
    <button type="submit" class="btn btn-primary btn-block" style="margin-top:10px;">ALTERAR</button>
    <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">VOLTAR</a>
</form>

contactSystem/Views/Contato/Excluir.cshtml
@model ContatoModels
@{
    ViewData["Title"] = "Excluir Contato";
}

<div class="text-center">
    <h1>Deseja apagar o contato @Model.Name ?</h1>
</div>
<div style="display:flex; align-items:center; justify-content:center; gap:10px;">
    <a class="btn btn-primary w-100" role="button" asp-controller="Contato" asp-action="Index">Cancelar</a>
    <a class="btn btn-danger w-100" role="button" asp-controller="Contato" asp-action="Delete" asp-route-id="@Model.Id">Confirmar</a>
</div>

contactSystem/Views/Contato/Index.cshtml
@model List<ContatoModels>
@{
    ViewData["Title"] = "Listagem de Contatos";
}


<div class="text-center">
    <div class="text-left">
        <a class="btn btn-primary" asp-controller="Contato" asp-action="Criar" style="color:white;" role="button">Adicionar Novo Contato +</a>
    </div>

    <h1 class="display-4">LISTAGEM DE CONTATOS</h1>

    <table class="table text-left">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">NOME</th>
          <th scope="col">E-MAIL</th>
          <th scope="col">CELULAR</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
            @if(Model != null && Model.Any())
            {
                foreach (var contato in Model)
                {
                     <tr>
                      <th scope="row">@contato.Id</th>
                      <td>@contato.Name</td>
                      <td>@contato.Email</td>
                      <td>@contato.Number</td>
                      <td>
                          <div class="btn-group" role="group" aria-label="Basic example">
                              <a role="button" class="btn btn-warning" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
                              <a role="button" class="btn btn-danger" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="Excluir">Apagar</a>
                          </div>
                      </td>
                    </tr> 
                }
            }
        </tbody>
    </table>



</div>

contactSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">BEM-VINDO</h1>
    <p>Sistema de controle de Contatos</p>
    
</div>

contactSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CONTROLE DE CONTATOS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">CONTATOS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Controle de Contatos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>